baseapp/urls.py
from django.contrib import admin
from django.urls import path
from baseapp import views
app_name = 'baseapp'

urlpatterns = [
    path('add/', views.add, name="add"),
    path('list/', views.list, name="list"),
    path('delete/<str:pk>/', views.deleteTask, name="delete"),
    path('logins/', views.logins, name="logins"),
    path('logouts/', views.user_logout, name="logouts"),
]

worklist/urls.py
from django.contrib import admin
from django.urls import path,include
from baseapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('baseapp/', include('baseapp.urls')),

]

baseapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Table(models.Model):
     user = models.ForeignKey(User,null=True,on_delete=models.CASCADE)
     title=models.CharField(max_length=100,default="no title",blank=False)
     desc = models.CharField(max_length=255, default="no desc", blank=False)
     Datetime = models.DateTimeField()

     def __str__(self) -> str:
          return self.title

baseapp/views.py
from datetime import datetime
from django.utils import timezone
from django.shortcuts import redirect, render
from baseapp.models import Table
from django.db.models.lookups import GreaterThan
from django.contrib import messages
from baseapp.form import user_info_Forms
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.contrib.auth.models import User
from .tasks import *
from django_celery_beat.models import PeriodicTask, CrontabSchedule
import json
import pytz
def home(request):
    return render(request,'baseapp/newhome.html')


@login_required
def user_logout(request):
    logout(request)
    messages.add_message(request, messages.SUCCESS, 'LOGGED OUT SUCCESSFULLY. ')
    return redirect("/baseapp/logins")


def list(request):
    if request.user.is_authenticated:
        currentime = datetime.now(pytz.timezone('Asia/Kolkata'))
        currdate = currentime.strftime("%Y-%m-%dT%H:%M")
        datalist = Table.objects.filter(Datetime__lte=currdate)
        
        for data in datalist:
           
            pt = PeriodicTask.objects.get(name=data.pk)
            pt.delete()
        
        datalist.delete()
       
        print(datalist)
        datalist=Table.objects.all().filter(user=request.user )
        print(datalist)
        return render(request,'baseapp/list.html',{"data":datalist})
    messages.add_message(request, messages.ERROR, 'LOGIN REQUIRED! ')
    return HttpResponseRedirect(reverse('baseapp:logins'))


def add(request):
    if request.user.is_authenticated:
        md=Table()
        user = User.objects.get(username=request.user)
        # print(user.username,user.email)
        currentime = datetime.now(pytz.timezone('Asia/Kolkata'))
        date_time = currentime.strftime("%Y-%m-%dT%H:%M")
        print(date_time)
        if request.method =='POST' :
            md.user=request.user
            md.title=request.POST["title"]
            md.desc=request.POST["Description"]
            md.Datetime = request.POST["DateTime"]
           
            # send_mail_task.apply_async(kwargs)
            if len(md.title) != 0 and len(md.desc) != 0 and md.Datetime>date_time :
                md.save()
                print(md.title)
                print(md.desc)
                print(md.Datetime)

                format ="%Y-%m-%dT%H:%M"
                
                Date = datetime.strptime(
                    md.Datetime, format)
                kwargs = (
                          user.username,
                          user.email,
                          md.title,
                          md.desc)
                schedule, created = CrontabSchedule.objects.get_or_create(
                hour=Date.hour, minute=Date.minute,month_of_year=Date.month,day_of_month=Date.day)
                task = PeriodicTask.objects.create(crontab=schedule,name=md.pk, task='baseapp.tasks.send_mail_task', args=json.dumps(kwargs))

                return redirect("/baseapp/list")
            else:
                messages.add_message(request, messages.ERROR, 'ENTER VALID DATA! ')
                return render(request,'baseapp/add.html')
        return render(request,'baseapp/add.html')
    messages.add_message(request, messages.ERROR, 'LOGIN REQUIRED! ')
    return HttpResponseRedirect(reverse('baseapp:logins'))
    

def deleteTask(request,pk):
    md = Table.objects.get(id=pk)
    pt = PeriodicTask.objects.get(name=md.pk)
    pt.delete()
    md.delete()
    return redirect('/baseapp/list')

def logins(request):
    if request.method == 'POST' and request.POST.get('case')== 'False':
        user_form=user_info_Forms(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            # sending mail to new register
            
            send_mail(
                'welcome mail to new user',
                'Hi '+ user.username+ "! you have registered successfully in our worlist wesbite",
                '',
                [user.email],
                fail_silently=False,
            )

            messages.add_message(request, messages.SUCCESS, 'REGISTERED SUCCESSFULLY ')
        else:
            messages.add_message(request, messages.ERROR, 'ENTER VALID DETAILS OR USERNAME ALREADY EXIST ! ')
            
    elif request.method == 'POST' and request.POST.get('case') == 'True':
        
         username = request.POST.get('username')
         password=request.POST.get('password')
         print(username,password)
         user =authenticate(username=username,password=password)
         if user:
            if user.is_active:
                login(request,user)
                messages.add_message(request, messages.SUCCESS, 'LOGGED IN SUCCESSFULLY! ')
                return redirect("/baseapp/add")
            else:
                messages.add_message(request, messages.ERROR, 'ACCOUNT IS NOT ACTIVE! ')
         else:
            messages.add_message(request, messages.ERROR, 'ACCOUNT IS NOT PRESENT! ')
    return render(request, 'baseapp/logins.html')

templates/baseapp/add.html
<!DOCTYPE html>
{% extends 'baseapp/base.html' %}
{% load static %}

{% block title %}

  <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@500&display=swap" rel="stylesheet">
<title>add page</title>

<link rel="stylesheet" href="{% static 'css/addcss.css' %}">
{% endblock title %}




{% block content %}
      
    <div class="main-addbox">
        {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible fade show " role="alert">
            <strong>{{message}}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        <div class="form">
           
            <h3 class="task-logo">TASK SCHEDULER</h3>
            <form action="" method="post" >
                {% csrf_token %}
                <p class="paragraphogAdd">
                    <input type="text" id="task-title" class="margin" placeholder="Enter Title here" name="title">
                    <textarea name="Description" id="Description" cols="50" rows="10" class="margin" placeholder="Write the Description"></textarea>
                </p>
                <p>
                    <label for="meeting-time" class="date-label">Choose a time for your appointment:</label>
                    <input type="datetime-local" id="meeting-time" name="DateTime" value="" min="2022-06-07T00:00"
                    max="2025-06-14T00:00">
                </p>
                    <div class="sub-form">
                        <input type="submit" class="add-btn" id="submitted" value="Add to the list">
                    </div>
    </form>
</div>

</div>

{% endblock content %}

templates/baseapp/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
       <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;1,500&family=Oxanium:wght@600&family=Raleway:ital,wght@0,600;0,700;1,600&family=Roboto:wght@300;500&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Glory:wght@300;600;700;800&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@500&display=swap" rel="stylesheet">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;1,500&family=Oxanium:wght@600&family=Raleway:ital,wght@0,600;0,700;1,600&family=Roboto:wght@300;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    {% block title %}
    {% endblock title %}
   <!-- Latest compiled and minified CSS -->

</head>

<body>
 <header>
        <nav class="nav">
            <p class="logo">WORKLIST</p>
            <ul class="ulist">
                <li><a href="{% url 'home' %}">HOME</a></li>
                <li><a href="{% url 'baseapp:add' %}" >ADD </a></li>
                <li><a href="{% url 'baseapp:list' %}"> LIST</a></li>
                {% if  user.is_authenticated  %}
                <li><a href="{% url 'baseapp:logouts' %}">LOGOUT</a></li>
                {% else %}
                <li><a href="{% url 'baseapp:logins' %}">LOGIN/REGISTER</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
   {% block content %}
   {% endblock content %}
   
   {% block script %}
   {% endblock script %}
   <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/baseapp/list.html
<!DOCTYPE html>
{% extends 'baseapp/base.html' %}
{% load static %}
{% block title %}
  <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@500&display=swap" rel="stylesheet">
<title>list page</title>
 <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock title %}


  {% block content %}
<div class="list main-addbox">
    <table class="margin table-modifiedcss">
        <thead>
            <tr>
                <th>DATE/TIME</th>
                <th>TITLE</th>
                <th id="descpt">DESCRIPTION</th>
                <th>ACTION</th>
            </tr>
        </thead>
        <tbody>
         {% for d in data %}
            <tr>
                <td class="sep">{{ d.Datetime }}</td>
                <td class="sep"> {{d.title}} </td>
                <td class="sep"> {{d.desc}} </td>
                <td class="sep"><a href="{% url 'baseapp:delete' d.id %} " class="dele" id="button" >DELETE</a> </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

templates/baseapp/logins.html
<!DOCTYPE html>
<html lang="en">
    
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;1,500&family=Oxanium:wght@600&family=Raleway:ital,wght@0,600;0,700;1,600&family=Roboto:wght@300;500&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Glory:wght@300;600;700;800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@500&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
        href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;1,500&family=Oxanium:wght@600&family=Raleway:ital,wght@0,600;0,700;1,600&family=Roboto:wght@300;500&display=swap"
        rel="stylesheet">
 <title>Sign in/Sign up</title>
<link rel="stylesheet" href="{% static 'css/login-register.css' %}">
</head>

<body>
    <header>
        <nav class="nav">
            <p class="logo">WORKLIST</p>
            <ul class="ulist">
                <li><a href="{% url 'home' %}">HOME</a></li>
                <li><a href="{% url 'baseapp:add' %}">ADD </a></li>
                <li><a href="{% url 'baseapp:list' %}"> LIST</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'baseapp:logouts' %}">LOGOUT</a></li>
                {% else %}
                <li><a href="{% url 'baseapp:logins' %}">LOGIN/REGISTER</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% for message in messages %}
   <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
       <strong>{{message}}</strong>
       <button type="button" class="close" data-dismiss="alert" aria-label="Close">
           <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
<div class="body">
    <div class="container">
        <div class="bg-box">
            <div class="signin">
                <h2>Already have an account ?</h2>
                <button class="btn">
                    sign in
                </button>
            </div>
            <div class="signup">
                <h2>Do you want sign up?</h2>
                <button class="btn">
                    sign up
                </button>
            </div>
        </div>
        <div class="form">
            <form action="" method="post" class="form-in">
                <h1>Sign In</h1>
                {% csrf_token %}
                <input type="hidden" name="case" value="True">
                <input type="text" name="username" placeholder="Username" >
                <input type="password"name="password" placeholder="Password"  >
                <input type="submit" class="btn" value="Sign in">
            </form>
            <form action=""  method="post" class="form-up act">
                <h1>Sign Up</h1>
                {% csrf_token %}
                <input type="hidden" name="case" value="False">
                <input type="text"  name="username" placeholder="Username">
                <input type="email" name="email" placeholder="Enter email">
                <input type="password" name="password" placeholder="Confirm Password">
                <input type="submit" class="btn" value="Sign up">
            </form>
    </div>
    </div>
 <script>
        let c=document.getElementsByClassName('form')[0];
        let b=document.getElementsByTagName('body')[0];
        let d=document.getElementsByClassName('form-up')[0];
        let sn=document.getElementsByClassName('btn')[0];
        let sup=document.getElementsByClassName('btn')[1];
        let forgpass=document.getElementById('forget');
        sup.onclick=function(){
c.classList.add('active');
b.classList.add('bg-active');
d.classList.remove('act');
}
sn.onclick=function(){
    c.classList.remove('active');
    b.classList.remove('bg-active');
    d.classList.add('act');
        }
    </script>

   
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</body>

</html>

templates/baseapp/newhome.html
<!DOCTYPE html>
{% extends 'baseapp/base.html' %}
{% load static %}
{% block title %}

  <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">

<title>home page</title>
 <link rel="stylesheet" href="{% static 'css/newhome.css' %}">
{% endblock title %}


  {% block content %}
<div class="box-modifiedcss">
   <img src=" {% static 'images/background.png' %}" alt="background" class="background-image-modifiedcss">
   <p class="content-modifiedcss">
    Hi my name is <b class="pan">Shivam Kumar Agarwal </b> ,and you are viewing my <span
                class="pan">Worklist</span> website.This is fully responsive website with mutiuser authentication design with help of Html, CSS            Javascript, SQlite3 & Django.
   </p>
</div>
{% endblock content %}